// vite-reactts-todomvc-2/src/@components/Footer.tsx
import { useAppDispatch, useAppSelector } from '@store/configureStore';
import {
  activeTodoCountSelector,
  completedTodoCountSelector,
} from '@store/todos/selectors';
import { removeCompletedAC } from '@store/todos/slice';
import { FilterEnum } from '@types';
import { pluralize } from '@utils/pluralize';

import FilterLink from './FilterLink';

const Footer = () => {
  const dispatch = useAppDispatch();
  const activeTodoCount = useAppSelector(activeTodoCountSelector);
  const completedTodoCount = useAppSelector(completedTodoCountSelector);

  const handleButtonClick = () => {
    dispatch(removeCompletedAC());
  };

  const renderClearButton = () => {
    if (completedTodoCount > 0) {
      return (
        <button type="button" className="clear-completed" onClick={handleButtonClick}>
          Clear completed
        </button>
      );
    }
    return null;
  };

  return (
    <>
      {activeTodoCount || completedTodoCount ? (
        <footer className="footer">
          <span className="todo-count">
            <strong>{activeTodoCount}</strong> {pluralize(activeTodoCount, 'item')} left
          </span>
          <ul className="filters">
            <FilterLink type={FilterEnum.SHOW_ALL}>All</FilterLink>
            <FilterLink type={FilterEnum.SHOW_ACTIVE}>Active</FilterLink>
            <FilterLink type={FilterEnum.SHOW_COMPLETED}>Completed</FilterLink>
          </ul>
          {renderClearButton()}
        </footer>
      ) : null}
    </>
  );
};

export default Footer;

// angular-ngrx-todomvc/src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import { clearCompletedTodoAC } from '../modules/todos/todos.actions';
import { activeTodoCountSelector } from '../modules/todos/todos.selectors';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent implements OnInit {
  currentFilter$: Observable<string>;
  countTodos$: Observable<number>;

  constructor(private store: Store<{ filter: string }>) {
    this.currentFilter$ = store.select('filter');
    this.countTodos$ = store.select(activeTodoCountSelector);
  }

  ngOnInit(): void {}

  clearCompleted() {
    this.store.dispatch(clearCompletedTodoAC());
  }
}

<footer class="footer">
    <span class="todo-count">
      <!-- {{ countTodos }} -->
       items left
    </span>
    <ul class="filters">
        <li>
            <a [routerLink]="['/']" [class.selected]="(currentFilter$ | async)== 'SHOW_ALL'">
            All
          </a>
        </li>
        <li>
            <a [routerLink]="['/','active']" [class.selected]="(currentFilter$ | async) == 'SHOW_ACTIVE'">
        Active
      </a>
        </li>
        <li>
            <a [routerLink]="['/','completed']" [class.selected]="(currentFilter$ | async) == 'SHOW_COMPLETED'">
        Completed
      </a>
        </li>
    </ul>
    <!-- <button class="clear-completed" (click)="clearCompleted()">Clear completed</button> -->
</footer>
