// vite-reactts-usecontext/src/todo-item/todo-item.tsx
import clsx from 'clsx';

import { TodoInterface } from '../context/todos-context.interface';

interface Props {
  todo: TodoInterface;
  // isEditing: boolean;
  // onChange: any;
  // onDoubleClick: any;
  onClick: any;
}

export const TodoItem = ({
  todo,
  // isEditing,
  // onChange,
  // onDoubleClick,
  onClick,
}: Props) => (
  <li
    className={clsx({
      completed: todo.completed,
      //   editing: isEditing,
    })}
  >
    <div className="view">
      <input
        className="toggle"
        type="checkbox"
        checked={todo.completed}
        // onChange={onChange(todo.id)}
      />
      <label
        htmlFor="itself"
        //    onDoubleClick={onDoubleClick(todo.id)}
      >
        {todo.title}
      </label>
      <button type="button" className="destroy" onClick={onClick} />
    </div>
    {/* isEditing */}
    {/* {isEditing ? <TodoEditInput /> : null} */}
  </li>
);

// vue3-todomvc/src/components/TodoItem.vue
<script setup lang="ts">
const props = defineProps(['todo', 'index'])
console.log('🚀 ~ props:', props)
</script>

<template>
  <li>
    <div class="view">
      <input type="checkbox" class="toggle" />
      <label>{{ todo.title }}</label>
      <button class="destroy"></button>
    </div>
  </li>
</template>
